/**
 * 1. Bring in LLM
 * 2. Build the graph
 * 3. Invoke the agent
 * 4. Add the memory
 */

import readline from "node:readline/promises";
import { ChatGroq } from "@langchain/groq";
import { TavilySearch } from "@langchain/tavily";
import { tool } from "@langchain/core/tools";
import * as z from "zod";
import { ToolNode } from "@langchain/langgraph/prebuilt";
import { MessagesAnnotation, StateGraph } from "@langchain/langgraph";

const search = new TavilySearch({
  maxResults: 3,
  topic: "general",
});

const calenderEvents = tool(
  async ({ query }) => {
    // Google calender logic goes here..
    return JSON.stringify([
      { title: "Meeting with Tanvir", time: "2PM", location: "Dhaka" },
    ]);
  },
  {
    name: "get-calender-events",
    description: "Call to get the calender events",
    schema: z.object({
      query: z.string().describe("The query to use in calender event search"),
    }),
  },
);

const tools = [search, calenderEvents];

// ToolNode is responsible for executing any tool calls generated by the LLM.
// It listens for tool_calls in the last AI message, matches them with the provided tools,
// runs the corresponding tool functions, and returns the results back into the graph state as messages.
const toolNode = new ToolNode(tools);

// 1. Bring in LLM
const llm = new ChatGroq({
  model: "openai/gpt-oss-120b",
  temperature: 0,
}).bindTools(tools);

async function callModel(state) {
  // call the llm
  console.log("calling the llm...");

  const response = await llm.invoke(state.messages); // sob message diye dey llm model ke response generate korte
  // console.log("response in callModel: ", response);
  return { messages: [response] };
}

/**
 * Conditional Edge
 */

function shouldContinue(state) {
  //   console.log(
  //     "message: ",
  //     state.messages[state.messages.length - 1].tool_calls,
  //   );

  const lastMessage = state.messages[state.messages.length - 1];

  if (lastMessage.tool_calls?.length) {
    return "tools";
  } else {
    return "__end__";
  }
}

// 2. Build the graph
const graph = new StateGraph(MessagesAnnotation)
  .addNode("llm", callModel)
  .addNode("tools", toolNode)
  .addEdge("__start__", "llm")
  .addEdge("tools", "llm")
  .addConditionalEdges("llm", shouldContinue);

const app = graph.compile();

async function main() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  while (true) {
    const userQuery = await rl.question("You: ");

    if (userQuery === "bye") {
      break;
    }

    const result = await app.invoke({
      messages: [
        {
          role: "user",
          content: userQuery,
        },
      ],
    });

    console.log(
      "result : ",
      result.messages[result.messages.length - 1].content,
    );
  }
}

main();
